#!/usr/bin/env python3
"""Editorial polish pass for the Catalan generated files.

This is not a machine translator. It applies a curated glossary and recurring
phrase fixes found during review, so the generated Catalan draft becomes usable
and keeps terminology consistent across the site.
"""

from __future__ import annotations

import re
from pathlib import Path


FILES = [
    Path("patis_portals_ca.md"),
    Path("README_CA.md"),
    Path("maps/printable-map-prompts_ca.md"),
    *sorted(Path("partials").glob("*_ca.md")),
]


PHRASES = {
    "Este documento es una adaptación fan no oficial per a taula amb quadrícula": "Aquest document és una adaptació fan no oficial per a taula amb quadrícula",
    "creada a partir de un texto base": "creada a partir d’un text base",
    "El nuevo título y presentación se usan": "El nou títol i la nova presentació es fan servir",
    "per a evitar confusión amb la obra original": "per evitar confusió amb l’obra original",
    "no implican afiliación, licencia ni aprobación por parte de sus titulares": "no impliquen afiliació, llicència ni aprovació per part dels seus titulars",
    "Patis i Portals es un juego de escaramuzas": "Patis i Portals és un joc d’escaramusses",
    "amb miniatures de 28 mm que no exige una gama concreta": "amb miniatures de 28 mm que no exigeix cap gamma concreta",
    "Usa les figuras que ya tengas o monta les tuyas propias": "Fes servir les figures que ja tinguis o munta les teves pròpies",
    "Un caballero espacial": "Un cavaller espacial",
    "gracias a la imaginación": "gràcies a la imaginació",
    "pot ser perfectamente el nuevo de la colla": "pot ser perfectament el nou de la colla",
    "Les proves utilizan dados poliédricos": "Les proves fan servir daus polièdrics",
    "normalmente tienen dificultad": "normalment tenen dificultat",
    "suma els modificadores y consigue": "suma els modificadors i aconsegueix",
    "Els modificadores de atributos": "Els modificadors d’atributs",
    "habilidades y equipo": "habilitats i equip",
    "son acumulativos": "són acumulatius",
    "siempre es una pífia": "sempre és una pífia",
    "siempre es un crític": "sempre és un crític",
    "Se pot medir y comprobar": "Es pot mesurar i comprovar",
    "antes de declarar una acción": "abans de declarar una acció",
    "Qué necesitas": "Què necessites",
    "Cuatro miniatures por jugador": "Quatre miniatures per jugador",
    "per a representar a els menuts": "per representar els menuts",
    "Miniaturas per a els Dolents": "Miniatures per als Dolents",
    "Si no tienes la figura perfecta": "Si no tens la figura perfecta",
    "cambia la descripción del enemigo y tira millas": "canvia la descripció de l’enemic i tira milles",
    "Dados D20": "Daus D20",
    "Un tauler de al menos": "Un tauler d’almenys",
    "Escenografía improvisada": "Escenografia improvisada",
    "todo lo que un menut pudiera encontrar por casa": "tot allò que un menut pugui trobar per casa",
    "Propiedades y palabras clave": "Propietats i paraules clau",
    "personaje no jugador enemigo": "personatge no jugador enemic",
    "miniatura controlada por un jugador": "miniatura controlada per un jugador",
    "no pot trazar línea de visión": "no pot traçar línia de visió",
    "emplea su activación": "fa servir la seva activació",
    "representan heridas y problemas persistentes": "representen ferides i problemes persistents",
    "se retira del juego": "es retira del joc",
    "se perd después de utilizarse": "es perd després d’utilitzar-se",
    "ignora toda la Defensa proporcionada": "ignora tota la Defensa proporcionada",
    "permite atacar": "permet atacar",
    "salvo que se indique": "tret que s’indiqui",
    "per a recargar": "per recarregar",
    "renuncia a su moviment": "renuncia al seu moviment",
    "pot realizar una acción": "pot fer una acció",
    "pot dispararse": "pot disparar-se",
    "antes de tener que recargar": "abans d’haver de recarregar",
    "Devolver al remitente": "Retorn al remitent",
    "quan recibe el ataque": "quan rep l’atac",
    "Si falla, recibe el impacto normalmente": "Si falla, rep l’impacte normalment",
    "Si tiene èxit": "Si té èxit",
    "devuelve el proyectil": "retorna el projectil",
    "pot responder": "pot respondre",
    "digno de Wimbledon": "digne de Wimbledon",
    "pot lanzarse": "pot llançar-se",
    "sense penalización": "sense penalització",
    "durante el resto de la ronda": "durant la resta de la ronda",
    "si recibe un impacto": "si rep un impacte",
    "el objeto queda destruido": "l’objecte queda destruït",
    "causal doble de daño": "causa el doble de dany",
    "También interactúa": "També interactua",
    "Bienvenidos a Cardisota": "Benvinguts a Cardisota",
    "Así que has decidido": "Així que has decidit",
    "Enhorabuena": "Enhorabona",
    "estás en la mejor compañía posible": "estàs en la millor companyia possible",
    "bosques verdes": "boscos verds",
    "ríos de montaña": "rius de muntanya",
    "según el folleto": "segons el fulletó",
    "sede internacional": "seu internacional",
    "pueblos": "pobles",
    "sus propias escuelas": "les seves pròpies escoles",
    "rivalidad supuestamente amistosa": "rivalitat suposadament amistosa",
    "el instituto más prestigioso": "l’institut més prestigiós",
    "estudiantes más distinguidos": "estudiants més distingits",
    "Universidad Estatal": "Universitat Estatal",
    "OFERTA DEL VERANO": "OFERTA DE L’ESTIU",
    "compra un Zumo de Duende": "compra un Suc de Follet",
    "llévate otro gratis": "emporta-te’n un altre de franc",
    "Se aplican términos": "S’apliquen termes",
    "Una historia local bastante regulera": "Una història local força regulera",
    "territorio pequeño y poco importante": "territori petit i poc important",
    "vecinos mucho más grandes": "veïns molt més grans",
    "La región se pobló": "La regió es va poblar",
    "recibió colonos": "va rebre colons",
    "Tras años de tensiones": "Després d’anys de tensions",
    "acabó convertida": "va acabar convertida",
    "famosa por enviar soldados": "famosa per enviar soldats",
    "Durante el caos": "Durant el caos",
    "quedó aislada": "va quedar aïllada",
    "la convirtió de repente": "la va convertir de cop",
    "al vora de la ruina": "a la vora de la ruïna",
    "Con determinación": "Amb determinació",
    "logró evitar": "va aconseguir evitar",
    "avanzar hacia": "avançar cap a",
    "estado del bienestar": "estat del benestar",
    "Hoy els tiempos oscuros": "Avui els temps foscos",
    "parecen haber quedado atrás": "semblen haver quedat enrere",
    "educación pública": "educació pública",
    "promete ser": "promet ser",
    "dejó tirades a muchas comunidades": "va deixar moltes comunitats abandonades",
    "aporte empleos e impuestos": "aporti feina i impostos",
    "Seguro que no sale nada mal": "Segur que no pot sortir malament",
    "¿SABÍAS QUE…?": "SABIES QUE…?",
    "antiguo cementerio": "antic cementiri",
    "vertedero de residuos tóxicos": "abocador de residus tòxics",
    "pueblo fantasma": "poble fantasma",
    "lugar ideal": "lloc ideal",
    "per a criar menuts": "per criar menuts",
    "Cada jugador controla": "Cada jugador controla",
    "Para crearla": "Per crear-la",
    "Elige cuatro": "Tria quatre",
    "Pon nombre y apellido": "Posa nom i cognom",
    "eligiéndolos o tirando": "triant-los o tirant",
    "Genera y asigna": "Genera i assigna",
    "Gasta les": "Gasta les",
    "Sal a buscar aventuras": "Surt a buscar aventures",
    "Volver entero es opcional": "Tornar sencer és opcional",
    "Atributos": "Atributs",
    "Elige una de estas matrices": "Tria una d’aquestes matrius",
    "Reparte sus cuatro valores": "Reparteix-ne els quatre valors",
    "como prefieras": "com prefereixis",
    "Valores disponibles": "Valors disponibles",
    "Ningún atributo": "Cap atribut",
    "resolver problemas": "resoldre problemes",
    "mentir a tus padres": "mentir als teus pares",
    "determina la Salut": "determina la Salut",
    "lo duro que resultal menut": "com de dur és el menut",
    "proves de fuerza": "proves de força",
    "saltos y golpes": "salts i cops",
    "También determinal": "També determina el",
    "impresionar a otros": "impressionar els altres",
    "hacer cosas que molan": "fer coses que molen",
    "Repositori estàtic amb la adaptación editorial": "Repositori estàtic amb l’adaptació editorial",
    "al castellano de España y a tauler de caselles": "al català i a tauler de caselles",
    "Abre `index.html`": "Obre `index.html`",
    "Manual HTML completo": "Manual HTML complet",
    "Fuente Markdown": "Font Markdown",
    "Versión catalana": "Versió catalana",
    "Parciales font": "Parcials font",
    "Hojas de estilo": "Fulls d’estil",
    "Hay dos formas válidas": "Hi ha dues formes vàlides",
    "Sube el repositorio": "Puja el repositori",
    "Ve a": "Ves a",
    "selecciona": "selecciona",
    "Elige la rama principal": "Tria la branca principal",
    "Guarda": "Desa",
    "usará": "farà servir",
    "punto de entrada": "punt d’entrada",
    "incluye": "inclou",
    "Haz push": "Fes push",
    "publica una copia estática limpia": "publica una còpia estàtica neta",
    "Si modificas": "Si modifiques",
    "puedes regenerar": "pots regenerar",
    "Ajusta la ruta de Python si usas otro entorno virtual": "Ajusta la ruta de Python si fas servir un altre entorn virtual",
}


TERMS = {
    "Este": "Aquest",
    "esta": "aquesta",
    "estos": "aquests",
    "estas": "aquestes",
    "Toda": "Tota",
    "toda": "tota",
    "todos": "tots",
    "todas": "totes",
    "Toda distància": "Tota distància",
    "reglas": "regles",
    "regla": "regla",
    "original": "original",
    "contradice": "contradiu",
    "recuadro": "requadre",
    "manda": "preval",
    "Resumen": "Resum",
    "resumen": "resum",
    "medición": "mesura",
    "Cuadrícula": "Quadrícula",
    "pulgadas": "polzades",
    "pulgada": "polzada",
    "dados": "daus",
    "dado": "dau",
    "resultado": "resultat",
    "Resultados": "Resultats",
    "redondea hacia arriba": "arrodoneix cap amunt",
    "arriba": "amunt",
    "abajo": "avall",
    "izquierda": "esquerra",
    "derecha": "dreta",
    "cuesta": "costa",
    "punto": "punt",
    "puntos": "punts",
    "cualquiera": "qualsevol",
    "ocho": "vuit",
    "únicamente": "únicament",
    "determinar": "determinar",
    "trazarse": "traçar-se",
    "cualquier": "qualsevol",
    "dirección": "direcció",
    "incluidas": "incloses",
    "centro": "centre",
    "atacante": "atacant",
    "bloqueada": "bloquejada",
    "atraviesa": "travessa",
    "ocupada": "ocupada",
    "bloquee": "bloquegi",
    "visión": "visió",
    "origen": "origen",
    "destino": "destí",
    "disparo": "tret",
    "señaladas": "indicades",
    "aleatorio": "aleatori",
    "aleatoria": "aleatòria",
    "sortea": "sorteja",
    "desplaza": "desplaça",
    "directamente": "directament",
    "sentido": "sentit",
    "opuesto": "oposat",
    "efecto": "efecte",
    "válidas": "vàlides",
    "radio": "radi",
    "dimensiones": "dimensions",
    "dentro": "dins",
    "área": "àrea",
    "temporada": "temporada",
    "verano": "estiu",
    "amigos": "amics",
    "días": "dies",
    "larguísimos": "llarguíssims",
    "misterio": "misteri",
    "imaginación": "imaginació",
    "siniestro": "sinistre",
    "pueblo": "poble",
    "resolver": "resoldre",
    "derrotar": "derrotar",
    "terminar": "acabar",
    "conseguir": "aconseguir",
    "tiempo libre": "temps lliure",
    "corazón": "cor",
    "chungo": "xungo",
    "juego": "joc",
    "escuela": "escola",
    "clases": "classes",
    "profesor": "professor",
    "profesora": "professora",
    "objeto": "objecte",
    "objetos": "objectes",
    "Objeto": "Objecte",
    "equipo": "equip",
    "Equipo": "Equip",
    "coste": "cost",
    "Coste": "Cost",
    "Efecto": "Efecte",
    "efecto": "efecte",
    "vez": "vegada",
    "repite": "repeteix",
    "supera": "supera",
    "automáticamente": "automàticament",
    "primera": "primera",
    "primer": "primer",
    "daño": "dany",
    "daños": "danys",
    "ataque": "atac",
    "ataques": "atacs",
    "distancia": "distància",
    "distancias": "distàncies",
    "alcance": "abast",
    "arma": "arma",
    "armas": "armes",
    "Arma": "Arma",
    "arrojadiza": "llancívola",
    "Arrojadiza": "Llancívola",
    "consumible": "consumible",
    "Consumible": "Consumible",
    "atuendo": "atuell",
    "atuendos": "atuells",
    "adultos": "adults",
    "adulto": "adult",
    "enemigo": "enemic",
    "enemigos": "enemics",
    "Enemigos": "Enemics",
    "visuales": "visuals",
    "despliegue": "desplegament",
    "Despliegue": "Desplegament",
    "sugerido": "suggerit",
    "fuerte": "fort",
    "cama": "llit",
    "camas": "llits",
    "frigorífico": "frigorífic",
    "fábrica": "fàbrica",
    "entrada": "entrada",
    "jaulas": "gàbies",
    "jaula": "gàbia",
    "jefe": "cap",
    "Jefe": "Cap",
    "palabras clave": "paraules clau",
    "Palabras clave": "Paraules clau",
    "especial": "especial",
    "Especial": "Especial",
    "comportamientos": "comportaments",
    "recompensa": "recompensa",
    "historia": "història",
    "Historia": "Història",
    "preparación": "preparació",
    "tesoro": "tresor",
    "fin": "final",
    "partida": "partida",
    "tienda": "botiga",
    "tiendas": "botigues",
    "artículos": "articles",
    "Artículo": "Article",
    "tipo": "tipus",
    "Tipo": "Tipus",
    "común": "comú",
    "comunes": "comuns",
    "raro": "rar",
    "raros": "rars",
    "prohibido": "prohibit",
    "Prohibido": "Prohibit",
    "legendario": "legendari",
    "Legendario": "Legendari",
    "documento": "document",
    "Documento": "Document",
    "manual": "manual",
    "texto": "text",
    "título": "títol",
    "presentación": "presentació",
    "licencia": "llicència",
    "aprobación": "aprovació",
}


REGEX_REPLACEMENTS = [
    (r"\ba els\b", "als"),
    (r"\bde els\b", "dels"),
    (r"\bper a els\b", "per als"),
    (r"\bel objectiu\b", "l’objectiu"),
    (r"\bel arma\b", "l’arma"),
    (r"\bel Ànim\b", "l’Ànim"),
    (r"\bel abast\b", "l’abast"),
    (r"\bel atac\b", "l’atac"),
    (r"\bel origen\b", "l’origen"),
    (r"\bel efecto\b", "l’efecte"),
    (r"\bel resultado\b", "el resultat"),
    (r"\bla obra\b", "l’obra"),
    (r"\bla aventura\b", "l’aventura"),
    (r"\bla activación\b", "l’activació"),
    (r"\buna acción\b", "una acció"),
    (r"\bde una\b", "d’una"),
    (r"\bde un\b", "d’un"),
    (r"\bamb un\b", "amb un"),
    (r"\bpor\b", "per"),
    (r"\by\b", "i"),
    (r"\bY\b", "I"),
    (r"\bpero\b", "però"),
    (r"\bPero\b", "Però"),
    (r"\bque no\b", "que no"),
    (r"\bya\b", "ja"),
    (r"\bsu\b", "el seu"),
    (r"\bsus\b", "els seus"),
    (r"\btu\b", "el teu"),
    (r"\btus\b", "els teus"),
    (r"\bte\b", "et"),
    (r"\bse\b", "es"),
    (r"\bson\b", "són"),
    (r"\bes\b", "és"),
    (r"\bEs\b", "És"),
    (r"\bestá\b", "és"),
    (r"\bestán\b", "són"),
    (r"\bpuedes\b", "pots"),
    (r"\bpueden\b", "poden"),
    (r"\bPuede\b", "Pot"),
    (r"\bpuede\b", "pot"),
    (r"\btienes\b", "tens"),
    (r"\btengan\b", "tinguin"),
    (r"\btiene\b", "té"),
    (r"\btienen\b", "tenen"),
    (r"\bhace\b", "fa"),
    (r"\bhacen\b", "fan"),
    (r"\bhacer\b", "fer"),
    (r"\butilizar\b", "utilitzar"),
    (r"\butilice\b", "utilitzi"),
    (r"\butiliza\b", "utilitza"),
    (r"\busar\b", "fer servir"),
    (r"\busas\b", "fas servir"),
    (r"\baparece\b", "apareix"),
    (r"\baparecen\b", "apareixen"),
    (r"\bcomienza\b", "comença"),
    (r"\bcomienzan\b", "comencen"),
    (r"\btermina\b", "acaba"),
    (r"\bterminan\b", "acaben"),
    (r"\bpierde\b", "perd"),
    (r"\bpierden\b", "perden"),
    (r"\bguanya\b", "guanya"),
    (r"\bobtiene\b", "obté"),
    (r"\bobtienen\b", "obtenen"),
    (r"\brecibe\b", "rep"),
    (r"\breciben\b", "reben"),
    (r"\brealiza\b", "fa"),
    (r"\brealizan\b", "fan"),
    (r"\bcalcula\b", "calcula"),
    (r"\baplica\b", "aplica"),
    (r"\bmueve\b", "mou"),
    (r"\bmueven\b", "mouen"),
    (r"\bhuye\b", "fuig"),
    (r"\bhuyen\b", "fugen"),
    (r"\bdeja\b", "deixa"),
    (r"\bdejan\b", "deixen"),
    (r"\bjunto\b", "al costat"),
    (r"\bmenos\b", "menys"),
    (r"\bmás\b", "més"),
    (r"\bdespués\b", "després"),
    (r"\bantes\b", "abans"),
    (r"\bmientras\b", "mentre"),
    (r"\bcuando\b", "quan"),
    (r"\bCuando\b", "Quan"),
    (r"\bsi\b", "si"),
    (r"\bSi\b", "Si"),
    (r"\bcomo\b", "com"),
    (r"\bComo\b", "Com"),
    (r"\bdesde\b", "des de"),
    (r"\bhacia\b", "cap a"),
    (r"\bfins a que\b", "fins que"),
    (r"\bper a que\b", "perquè"),
    (r"\bper a navegar\b", "per navegar"),
    (r"\bper a generar\b", "per generar"),
    (r"\bper a evitar\b", "per evitar"),
]


def protect_code(text: str) -> tuple[str, list[str]]:
    protected: list[str] = []

    def keep(match: re.Match[str]) -> str:
        protected.append(match.group(0))
        return f"§§PROTECTED{len(protected) - 1}§§"

    text = re.sub(r"```[\s\S]*?```", keep, text)
    text = re.sub(r"`[^`\n]+`", keep, text)
    text = re.sub(r"\]\([^)]+\)", keep, text)
    text = re.sub(r"<[^>\n]+>", keep, text)
    return text, protected


def restore_code(text: str, protected: list[str]) -> str:
    for index, value in enumerate(protected):
        text = text.replace(f"§§PROTECTED{index}§§", value)
    return text


def polish(text: str) -> str:
    text, protected = protect_code(text)
    for src, dst in sorted(PHRASES.items(), key=lambda item: len(item[0]), reverse=True):
        text = text.replace(src, dst)
    for src, dst in sorted(TERMS.items(), key=lambda item: len(item[0]), reverse=True):
        text = re.sub(rf"\b{re.escape(src)}\b", dst, text)
    for pattern, repl in REGEX_REPLACEMENTS:
        text = re.sub(pattern, repl, text)
    text = text.replace("per per", "per")
    text = text.replace("i i", "i")
    text = text.replace("l’l’", "l’")
    return restore_code(text, protected)


def main() -> None:
    for path in FILES:
        if not path.exists():
            continue
        original = path.read_text(encoding="utf-8")
        updated = polish(original)
        path.write_text(updated, encoding="utf-8")
        print(path)


if __name__ == "__main__":
    main()
